version: '3'

services:
  redis:
    image: redis:alpine
    container_name: socket-redis-game
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./redis-volume:/data

  server:
    container_name: socket-node-game
    build :
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - '8080:8080'
    depends_on:
      - redis


